dist: focal
language: python
python:
  - "3.7"
  - "3.8"
  - "3.9-dev"
env:
  - POSTGRESQL_VERSION=12
  - POSTGRESQL_VERSION=11
  - POSTGRESQL_VERSION=10
  - POSTGRESQL_VERSION=9.6
before_install:
  - sudo service postgresql stop && sudo service postgresql start $POSTGRESQL_VERSION
install:
  - pip install -r requirements.txt
  - pip install -r tests/test-requirements.txt
before_script:
  - psql -c 'CREATE DATABASE piccolo;' -U postgres
  - psql -c "CREATE USER piccolo PASSWORD 'piccolo';" -U postgres
  - psql -c "GRANT ALL PRIVILEGES ON DATABASE piccolo TO piccolo;" -U postgres
  - psql -c "CREATE EXTENSION IF NOT EXISTS \"uuid-ossp\";" -d piccolo -U postgres
script:
  - flake8 piccolo
  - mypy piccolo
  - cd tests && ./travis.sh
after_success:
  - cd .. && coveralls
